### ISSUE TITLE
Update for version 1.8

### ISSUE THREAD

**Issue by mar-v-in** [google/exposure-notifications-internals#27]
The German Corona-Warn-App is now using a version 18.0.3 of the exposure notification library ([see here](https://github.com/corona-warn-app/cwa-app-android/blob/v1.13.0-RC9/Corona-Warn-App/libs/play-services-nearby-exposurenotification-18.0.3.aar)).
- [x] The [release notes](https://developers.google.com/android/exposure-notifications/release-notes) currently do not mention a 1.8 release (which the 18.0.3 is presumably referring to)
- [ ] The API reference now mentions a [requestPreAuthorizedTemporaryExposureKeyHistory()](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient#requestPreAuthorizedTemporaryExposureKeyHistory()) method that does not appear in the [API documentation](https://developers.google.com/android/exposure-notifications/exposure-notifications-api)
- [ ] This repository has not been updated since October 2020 and thus presumably also doesn't document any of the changes of version 1.8 yet.

**Comment by NewGyu** [comment]
I don't understand well why this repository is published. This seems to provide sample codes for developers who works for public health organization. But this repository doesn't show us version information clearly, and this is probably not the source code for the least EN. That confuses the developers.... such as #19 .

I hope that the informations below are descried in README.
- [ ]  What purpose is this repository published for?
- [ ]  Which version of the snapthot is contained?

And if possible, please update this repository when the new EN version is released.

**Comment by nic0lette** [comment]
This repository is a frozen single instance of the internal code used by the Exposure Notifications module inside Google Play Services. It was published to provide more transparency on how the system worked internally.

The code was actually not primarily aimed for developers at public health organizations. That code is located in the [server](https://github.com/google/exposure-notifications-server), [verification server](https://github.com/google/exposure-notifications-verification-server), and [Android client](https://github.com/google/exposure-notifications-android) repositories.

It's true that there has been quite a lot of development since this version was released. The code here will not be updated at this time, however.

**Comment by dylangerdaly** [comment]
That's a shame, sounds like Google is indirectly endangering people by not updating the code. There's a significant amount of people that don't use Google Play Services, opting for an open alternative, but would still like to "Do their part" in using a COVID-19 tracing application.

**Comment by rachyandco** [comment]
This could be even illegal under certain jurisdictions. 

https://www.fedlex.admin.ch/eli/cc/2015/297/de#art_60_a

`Der Quellcode und die technischen Spezifikationen aller Komponenten des PT-Systems sind öffentlich. Die maschinenlesbaren Programme müssen nachweislich aus diesem Quellcode erstellt worden sein.`

Article 60a of the Swiss law on epidemies states that all parts of the proximity tracing code source should be open.
